### ISSUE TITLE
Optimization problems

### ISSUE THREAD

**Issue by aD0UBLEj** [chuggafan/Prime-Search#2]

**Comment by chuggafan** [comment]
Ok, for this i'm going to have to show you the relevant code, give me a minute and i'll grab organize everything

**Comment by aD0UBLEj** [comment]
Language sufficiently understandable? I only know python and java really and the actual maths behind this

**Comment by chuggafan** [comment]
`        static bool lucasPrimeTests(int p)
        {
                for (; u < p - 2; u++)
                {
                    x = ((x * x) - 2) % k;
                    GC.Collect();
                    if (x == 0)
                    {
                        return true;
                    }
                return false;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.StackTrace);
                Thread.Sleep(100000);
                return false;
            }
        }`
also: C# is basically java, this is the relevant part

**Comment by aD0UBLEj** [comment]
The final value you need is S_(p-2) so you may need one more term on the loop?

**Comment by chuggafan** [comment]
well, that can be done easily, so just edit that part to be <= and we're all good?

**Comment by aD0UBLEj** [comment]
I _think_ so, or < p-1

**Comment by chuggafan** [comment]
<= p-2 is in this case equivlent to < p-1 as the number we're checking is an integer

**Comment by aD0UBLEj** [comment]
Should be good then as long as initial value S_0 is set to 4 and final result is actually S_(p-2) (and no rounding errors occur)

**Comment by chuggafan** [comment]
no rounding errors can occur, S_0 was gaurenteed set to 4, i actually had a bug before where i did saved to it the number above, i fixed that just now aswell, will tag a new release rn ;)
